### PR TITLE
allow whitelist filter to keep only wanted files

### PR DESCRIPTION
**Pull request by jdeniau**
Hi, 

Thanks for your extension first, it will really help me for upgrades !

I needed to filter only certain files calling `trigger_error`, so I added a `whitelist` option to do so.

I did not really completed the unit tests because when I run `phpunit` it throw a lot of errors.
I think it has something to do with the `.phpt` files but can you give me an hint about this ?

Thanks

### CODE REVIEW

**Comment by caciobanu** [comment]
I'm not sure I'll get this in 1.x as I'm thinking at a 2.x version that has the same output as https://symfony.com/doc/current/components/phpunit_bridge.html.

Current output of a list of steps doesn't provide a clear message where the deprecated call took place in code.

**Comment by jdeniau** [comment]
it seems a great output yes (it was my inspiration too before I found your package).

But I don't see why this could not be merged in 1.x ? (It has nothing to do with the output), unless you want to re-factor a lot of things that impact the extension ?
In that case is there any work in progress on the v2 where I can rebase my PR ?

Thanks

**Comment by caciobanu** [comment]
I'm considering it for v2 because someone might depend on current output. Work on v2 didn't start yet.

**Comment by caciobanu** [comment]
@jdeniau I pushed to master the changes for v2 which mimics the symfony/phpunit-bridge output format.

**Comment by jdeniau** [comment]
OK I will look at this possibly then

**Comment by caciobanu** [comment]
I will also think about the feature requested in this PR. I'm more into a blacklist instead of a whitelist for now.

**Comment by caciobanu** [comment]
Released v2: https://github.com/caciobanu/behat-deprecation-extension/releases/tag/v2.0.0

**Comment by jdeniau** [comment]
Hi,

I updated the pull request to work with master. I also replaced the `whitelist` by a `ignoreDeprecations`, than finaly makes sense for me to 😉

**Comment by jdeniau** [comment]
I tried to add a test but I do not really understand how to change the behat configuration with the `.phpt` files.

Can you help me with that ? 

Moreover, the tests are failing on PHP5.4, I do not know why, but PHP 5.4 is unsupported since 3 Sep 2015. (The 5.x branch won't be supported in 15 days too !)

**Comment by caciobanu** [comment]
This looks great, but ignoring files could lead to ignoring potential deprecation messages which the user may be interested in. A better way to do this is to ignore deprecation messages instead.

**Comment by jdeniau** [comment]
It's precisly what I opened this PR: 
ignoring deprecation of `src/` for example, to check external dependencies deprecation in order to upgrade.

If I ignore deprecation messages, I would end up without a huge number of line (because a lot of different deprecation messages), and it will be very sensible to changes.

I do not really see the point of ignoring a particular error message, but it's maybe because the way I see things in my codebase.

A possible evolution is to change:
```yaml
Caciobanu\Behat\DeprecationExtension:
  mode: null                                                                                                                                
  ignoreDeprecations:
    - '#\/MyApp\/#'
```

By:
```yaml
Caciobanu\Behat\DeprecationExtension:
  mode: null                                                                                                                                
  ignoreDeprecations:
    - { file: '#\/MyApp\/#' } # ignore all deprecation in `MyApp`
    - { message: '#^The argument "foo" is deprecated$#' } # ignore all message matching the regexp
    - { file: '#\/MyOtherApp\/#', message: '#^The argument "bar" is deprecated$#' } # ignore all message matching the regexp AND in a `MyOtherApp` folder
```

What do you think ?

**Comment by caciobanu** [comment]
The second proposal looks nice. Also we could rename ignoreDeprecations to ignore.

**Comment by caciobanu** [comment]
@jdeniau I've updated the implementation.

**Comment by jdeniau** [comment]
@caciobanu Looks good to me !

The failing test is PHP 5.4, I don't think we should put any effort in this ^^

**Comment by caciobanu** [comment]
Merging this. I will decide after what I'll do with the failing tests on PHP 5.4.

**Pull request merged**
