### PR TITLE
Fix problem with examples in behat tests, we don't need to check the …

### PR DESCRIPTION
**Pull request by wikimatze**
…text of the steps because steps lines are matching to scenario

### CODE REVIEW

**Comment by caciobanu** [comment]
Thank you @wikimatze !

**Comment by wikimatze** [comment]
You're welcome, running tests are not so easy, there were some hard coded travis-ci path inside you're project.

**Comment by caciobanu** [comment]
I fixed the problem with hardcoded travis paths on master.

**Comment by wikimatze** [comment]
Thank you very much.

**Comment by fbourigault** [comment]
@caciobanu is it possible to get a release including this PR? It will also fix an error when a deprecation notice is triggered in a `Scenario Outline` as the `$step->getText()` contains placeholders but `$stepNode->getText()` doesn't.

**Comment by caciobanu** [comment]
@fbourigault done.

**Comment by fbourigault** [comment]
Thank you!

**Pull request merged**
